### ISSUE TITLE
无法获取根目录数据？

### ISSUE THREAD

**Issue by pangdhai** [wesley2012/YoudaoNoteExport#4]
nse = self.post(
            'https://note.youdao.com/yws/api/personal/file?method=getByPath&keyfrom=web&cstk=%s' % self.cstk, data=data)

        print(response)
        #print('getRoot:' + response.content)
        jsonObj = json.loads(response.content)

<Response [500]>
Traceback (most recent call last):
  File "H:/python/project/cnki/youdaonote.py", line 147, in <module>
    sess.getAll(saveDir, doc_type)
  File "H:/python/project/cnki/youdaonote.py", line 126, in getAll
    rootId = self.getRoot()
  File "H:/python/project/cnki/youdaonote.py", line 61, in getRoot
    return jsonObj['fileEntry']['id']

**Comment by gaory1** [comment]
刚试了一下，我这里没问题...
